environment:
  access_token:
    secure: QmvdmXy3CdTojdtsWPqH7IzlXDCpnWP3P5XjsVtulciz2aa6wUVYR+qb088RWexv
  YARN_CACHE_FOLDER: .yarn

branches:
  only:
  - master
  except:
  - openshift

skip_commits:
  author: AppVeyor

cache:
- node_modules
- .yarn

image: Ubuntu

init:
- git config --global core.autocrlf false
- git config --global credential.helper store
- ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
- git config --global user.name "AppVeyor"
- git config --global user.email "error@error-unlimited.net"
- nvm install latest
- nvm use latest

install:
- git checkout master
- yarn install --non-interactive --frozen-lockfile --production=false

test_script:
- node --version
- yarn --version
- env

build_script:
- yarn build

deploy_script:
- yarn deploy
