version: 2.0

defaults: &defaults
  docker:
  - image: circleci/node:latest
  working_directory: ~/src/github.com/errorx666/r3
  environment:
    YARN_CACHE_FOLDER: ~/.yarn

jobs:
  build:
    <<: *defaults
    steps:
    - run: git config --global core.autocrlf false
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        - v1-dependencies-
        - yarn
    - run: yarn install --non-interactive --frozen-lockfile --production=false
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "yarn.lock" }}
    - save_cache:
        paths:
        - "{{ .Environment.YARN_CACHE_FOLDER }}"
        key: yarn
    - run: yarn build
    - persist_to_workspace:
        root: .
        paths:
        - dist
        - node_modules
        - package.json
        - yarn.lock
    - store_artifacts:
        path: dist
    - store_artifacts:
        path: package.json
    - store_artifacts:
        path: yarn.lock
    - add_ssh_keys:
        fingerprints:
        - '8c:7b:60:71:cb:10:d4:ae:30:ad:af:47:f6:30:ba:ad'
    - run: git config --global user.name "CircleCI"
    - run: git config --global user.email "error@error-unlimited.net"
    - run: yarn deploy
