version: 2.0

defaults: &defaults
  docker:
  - image: circleci/node:latest
  working_directory: ~/src/github.com/errorx666/r3

jobs:
  build:
    <<: *defaults
    context: github
    steps:
    - run: git config --global core.autocrlf false
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        - v1-dependencies-
    - run: yarn install --non-interactive --frozen-lockfile --production=false
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "yarn.lock" }}
    - run: yarn build
    - store_artifacts:
        path: dist
    - store_artifacts:
        path: package.json
    - store_artifacts:
        path: yarn.lock
    - run: git config credential.helper cache
    - run: echo "https://${GITHUB_TOKEN}:x-oauth-basic@github.com" > ~\.git-credentials
    - run: git config --global user.name "CircleCI"
    - run: git config --global user.email "error@error-unlimited.net"
    - run: yarn deploy
